# Generated by Django 5.0.6 on 2024-06-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coffee',
            table='coffee_table',
        ),
    ]
